<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>testing</name>
  <version>0.0.0</version>
  <description>Standalone vehicle-control stack for calibration and testing.</description>
  <maintainer email="wilp@todo.todo">wilp</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>ackermann_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>vesc_driver</exec_depend>
  <exec_depend>urg_node2</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
