/**:
  ros__parameters:
    wheelbase: 0.33
    speed_to_erpm_gain: 4123.4
    speed_to_erpm_offset: 0.0

    steering_to_servo_gain: 1.2135
    steering_to_servo_offset: 0.5405

    max_steering_angle: 0.36

    servo_min: 0.15
    servo_max: 0.85

    max_speed: 8.0
    min_speed: -8.0